### ISSUE TITLE
Consider dropping script execution

### ISSUE THREAD

**Issue by dlorenc** [sigstore/sget-rs#46]
**Description**

I think we should consider dropping script execution, or at least make it off by default.  curl | bash still requires bash :)

Executing a binary directly seems a bit scary. I can see running a script in a shell, but would we want to run anything?

**Comment by lukehinds** [comment]
There is a `--no-exec` flag which can be coupled with `--outfile` (so someone could run it directly afterwards)

I am inclined to agree if we support other media types as per #49 

How about a `--exec` , so the default is verify but don't execute? Someone can then run with `--outfile` and execute afterwards.

**Comment by luhring** [comment]
What impact would this have on the intended usage (e.g. what's shown in project READMEs' installation instructions)? Something like this?

```
sget ... | sh
```

**Comment by imjasonh** [comment]
Yeah, I think that's what's being proposed basically. Instead of `sget` being responsible for fetching and executing, only make it responsible for securely fetching, then printing to stdout, where it can be redirected to a file or piped to `sh`.

FWIW I'm +1 on making `sget` responsible for less, and making it more single-purpose by default. It should just be as simple as changing the default to `--no-exec=true` (or probably more readable, `--exec=false`, as in https://github.com/sigstore/sget/issues/46#issuecomment-997344186).

We might also want to support `--outfile=-` which prints the fetched contents to stdout, so a user can ` | sh`. Maybe even make `-` the default?

**Comment by dlorenc** [comment]
Dropping the exec all together would work too - it might even be preferable.

This is both a pro and a con, but execution seems like it could be used for a privilege escalation attack in environments that aren't expected to be able to remotely fetch code and execute it.

**Comment by lukehinds** [comment]
I am not keen on dropping it altogether , as this means people will just do the following:

`sget <something>` | bash something`

I prefer we go with changing to don't execute by default, only execute when the flag is provided.
